name: Rigenera Master
on:
  push:
    branches:
      - main
    paths:
      - plugins/**
  workflow_dispatch:

jobs:
  generate:
    name: Rigenera Plugin Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9 # v4
        with:
          python-version: '3.8'
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Genera PluginMaster
        run: python generate_master.py
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # v9
        with:
          author_name: Priscilla
          author_email: noreply@ahd-creative.agency
          message: Rigenera PluginMaster
